[project]
name = "nuke-tools-lxm"
version = "0.8.3"
description = "Collection of script & resources for Foundry's Nuke software."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "colour-science>=0.4.6",
]

[dependency-groups]
dev = [
    "black>=26.5.1",
    "types-pyside2>=5.15.2.1.8",
]
